### PR TITLE
Don’t attempt to initialise when running under FastBoot

### PR DESCRIPTION
**Pull request by rlivsey**
This lets apps run under fastboot which have this addon installed

Obviously the addon will no longer work in Fastboot, but I don't see a scenario where that would be wanted anyway!

### CODE REVIEW

**Comment by buritica** [comment]
Hey @rlivsey I'm not sure I understand the use case. Why would you not want this addon to run on fastboot apps? I'm not super familiar w fastboot, know it's server side rendering but I fail to see how that relates to not loading stripe.

thx!

**Comment by rlivsey** [comment]
I blame not enough coffee, I think I tried to solve the wrong problem.

The real problem is that currently the addon fails under FastBoot, because it appears Stripe either isn't loading or at least hasn't loaded at the time the initializer kicks in. This means `Stripe.setPublishableKey(config.stripe.publishableKey);` fails and takes the whole app down with it.

Preventing any of this from loading obviously "fixes" the issue and got my app to boot, but the real solution would be figuring out why `Stripe` isn't available at this point as you're right that it should *just work*.

Feel free to close this and I'll dig in and issue a more correct PR in the (hopefully) near future!

**Comment by buritica** [comment]
oh, makes a lot of sense.

Do you think you could help me make a small isolated use case in jsbin that replicates this, that way we can figure out what the best approach is.

Thanks again!

**Comment by esistgut** [comment]
Any update on this? The component prevents running in Fastboot mode.

**Pull request closed without merging**
