### PR TITLE
Add stripe client side validations

### PR DESCRIPTION
**Pull request by dasnixon**
Piggybacking off of @sescobb27, but this seems a lot more minimal. Definitely useful to have the client side validations available.

### CODE REVIEW

**Comment by dasnixon** [comment]
@buritica is this still something you are maintaining?

**Comment by buritica** [comment]
hi sorry, for some reason I missed the PR email! yes!

**Comment by buritica** [comment]
not sure if we should add tests that verify the existence of these methods or not. thoughts?

**Comment by dasnixon** [comment]
You're talking about safeguarding against `Stripe` right? And not actual unit tests that check for that function on Stripe object? If it's the latter, it seems pretty pointless to me. As for the former, that's a smart idea, and I do hope that stripe doesn't release breaking changes on a version. Let me know what you think and I can update the PR.

**Comment by buritica** [comment]
the former, a check on whether changes on the underlying library could affect upgrades

**Comment by dasnixon** [comment]
:+1: will add that and let you know

**Comment by dasnixon** [comment]
@buritica updated, sorry took a bit of time.

**Comment by buritica** [comment]
no problem, it looks good! I'll check it out this week and publish!

**Comment by buritica** [comment]
this is live, thanks @dasnixon

**Pull request merged**
