### PR TITLE
Upgrade Ember CLI to 2.5

### PR DESCRIPTION
**Pull request by samselikoff**

### CODE REVIEW

**Comment by samselikoff** [comment]
@ridedevops how do I get the API key to run tests?

**Comment by buritica** [comment]
you would get it with your own stripe account

--
Juan Pablo Buriticá
VP of Engineering - Ride
t: @buritica




On Sun, Apr 24, 2016 at 12:11 PM -0700, "Sam Selikoff" <notifications@github.com> wrote:












@ridedevops how do I get the API key to run tests?

**Comment by samselikoff** [comment]
gotcha. How did you set up Travis to run these tests? basically, is there a way we can get a shared/test key so PRs and such can run the whole suite?

**Comment by buritica** [comment]
You can set the key as an [environment variable in travis](https://docs.travis-ci.com/user/environment-variables/.

You would set it as `STRIPE_PUBLISHABLE_KEY` and then it'll be available in your tests. 

Not sure a shared key is a great idea, because if we decide to rollover our keys it would break everyone else's builds. Stripe will give you a set of test and live keys to use when you create an account, which if you're going to use this lib you'll need. I recommend you use your test key, you only set it up once on your CI and it should work.

Let me know if I can help with anything else!

**Comment by buritica** [comment]
If I'm not wrong, these builds should be running against our Travis setup, so it should be using our key which may have been rolled over after our last release. I've updated the key and rerun the tests, maybe that should fix it.

**Comment by samselikoff** [comment]
Sorry - I'm actually talking about your CI server (the Travis server used for this repo). For example, I wanted to get this PR working, but it fails bc it didn't have a key.

I looked at the original test suite and I had assumed you set it in your Travis account (again your Travis setup for this OSS repo). Maybe the ENV vars don't carry over to PRs?

**Comment by buritica** [comment]
Ok, so I've set the key as not encrypted and now your PR passed. I'll leave it as is so hopefully any others can share the same. Thanks for your contribution!

**Comment by samselikoff** [comment]
Perfect! I think this PR is ready to go then.

**Comment by buritica** [comment]
this has been published to npm now, thanks again!

**Pull request merged**
